import { test, expect } from '@playwright/test';

test('登録・編集・年次/月次・削除・再読み込み', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByText('デモモード（入力内容は保存されません）')).toBeVisible();
  await page.getByRole('button', { name: '＋ 車両を登録' }).click();
  await page.getByLabel('登録番号').fill('見本 300 わ 0099');
  await page.getByLabel('車名・型式').fill('見本テスト車両');
  await page.getByLabel('排気量（cc）').fill('1500');
  await page.getByLabel('取得日', { exact: true }).fill('2024-04-01');
  await page.getByLabel('事業供用日').fill('2024-04-01');
  await page.getByLabel('取得価額（円・税抜）').fill('3000000');
  await page.getByRole('button', { name: '登録する', exact: true }).click();
  await expect(page.getByRole('heading', { name: '見本テスト車両' })).toBeVisible();
  const annual = page.getByRole('table', { name: '年次償却スケジュール' });
  await expect(annual.getByRole('cell', { name: '2,001,000円', exact: true })).toBeVisible();
  await page.getByLabel('月次の事業年度').selectOption('2027-03');
  await expect(page.getByRole('table', { name: '月次償却スケジュール' }).getByRole('cell', { name: '332,666円', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '編集する' }).click();
  await page.getByLabel('車名・型式').fill('見本編集後');
  await page.getByRole('button', { name: '変更を反映' }).click();
  await expect(page.getByRole('heading', { name: '見本編集後' })).toBeVisible();
  await page.getByRole('button', { name: '一覧に戻る' }).click();
  await page.getByPlaceholder('登録番号・車名').fill('0099');
  await expect(page.getByRole('table', { name: '車両一覧' }).getByRole('row')).toHaveCount(2);
  await page.getByRole('button', { name: '見本編集後', exact: true }).click();
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: '車両を削除', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('車両を削除しました');
  await page.reload();
  await expect(page.getByRole('table', { name: '車両一覧' }).getByRole('row')).toHaveCount(4);
  expect(await page.evaluate(() => ({ local: Object.keys(localStorage), session: Object.keys(sessionStorage) }))).toEqual({ local: [], session: [] });
});

test('設定・絞り込み・EVの手動選択・再読み込み', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('店舗', { exact: true }).selectOption('テスト第二店');
  await expect(page.getByRole('table', { name: '車両一覧' }).getByRole('row')).toHaveCount(2);
  await page.getByLabel('クラス', { exact: true }).selectOption('EV');
  await expect(page.getByText('該当する車両がありません')).toBeVisible();
  await page.getByRole('button', { name: '絞り込みを解除' }).click();
  await page.getByLabel('基準月').fill('2024-04');
  await expect(page.getByText('2024年4月 ▦', { exact: true })).toBeVisible();
  await expect(page.getByText('7,508,250円', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '設定', exact: true }).click();
  await page.getByLabel('会社名').fill('架空テスト会社');
  await page.getByLabel('決算月').selectOption('12');
  await page.getByLabel('償却方法の初期値').selectOption('straight');
  await page.getByLabel('端数処理').selectOption('ceil');
  await page.getByRole('button', { name: '設定を反映' }).click();
  await expect(page.getByRole('status')).toContainText('計算を更新');
  await page.getByRole('button', { name: '車両台帳', exact: true }).click();
  await page.getByRole('button', { name: '＋ 車両を登録' }).click();
  await expect(page.getByLabel('償却方法', { exact: true })).toHaveValue('straight');
  await page.getByLabel('登録番号').fill('見本 300 わ 0100');
  await page.getByLabel('車名・型式').fill('見本EV');
  await page.getByLabel('燃料', { exact: true }).selectOption('ev');
  await page.getByLabel('取得日', { exact: true }).fill('2024-04-01');
  await page.getByLabel('事業供用日').fill('2024-04-01');
  await page.getByLabel('取得価額（円・税抜）').fill('3000000');
  await page.getByRole('button', { name: '登録する', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('手動選択');
  await page.getByLabel('耐用年数の上書き').selectOption('4');
  await page.getByLabel('上書き理由').fill('架空デモの仮設定・要確認');
  await page.getByRole('button', { name: '登録する', exact: true }).click();
  await expect(page.getByRole('heading', { name: '見本EV', exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText('架空レンタカー（デモ）').first()).toBeVisible();
  await expect(page.getByRole('button', { name: '見本EV', exact: true })).toHaveCount(0);
  await expect(page.getByText('最終的な税務判断は顧問税理士にご確認ください')).toBeVisible();
});

test('外部通信・エラーなし、メモに入力したHTMLを文字列で表示', async ({ page }) => {
  const errors: string[] = []; const external: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => { if (new URL(request.url()).hostname !== '127.0.0.1') external.push(request.url()); });
  await page.goto('/');
  await page.getByRole('button', { name: '見本コンパクト', exact: true }).click();
  await page.getByRole('button', { name: '編集する' }).click();
  await page.getByLabel('メモ', { exact: true }).fill('<img src=x onerror=alert(1)>');
  await page.getByRole('button', { name: '変更を反映' }).click();
  await expect(page.getByText('<img src=x onerror=alert(1)>', { exact: true })).toBeVisible();
  expect(await page.locator('img').count()).toBe(0);
  expect(external).toEqual([]); expect(errors).toEqual([]);
});
